export const imgsData = [{
    index: '1',
    src: 'img1.jpg'
  }, {
    index: '2',
    src: 'img2.jpg'
  }, {
    index: '3',
    src: 'img3.jpg'
  }, {
    index: '4',
    src: 'img4.jpg'
  }, {
    index: '5',
    src: 'img5.jpg'
  }, {
    index: '6',
    src: 'img6.jpg'
  }, {
    index: '7',
    src: 'img7.jpg'
  }, {
    index: '8',
    src: 'img8.jpg'
  }, {
    index: '9',
    src: 'img9.jpg'
  }, {
    index: '10',
    src: 'img10.jpg'
  }, {
    index: '11',
    src: 'img1.jpg'
  }, {
    index: '12',
    src: 'img2.jpg'
  }, {
    index: '13',
    src: 'img3.jpg'
  }, {
    index: '14',
    src: 'img4.jpg'
  }, {
    index: '15',
    src: 'img5.jpg'
  }, {
    index: '16',
    src: 'img6.jpg'
  }, {
    index: '17',
    src: 'img7.jpg'
  }, {
    index: '18',
    src: 'img8.jpg'
  }, {
    index: '19',
    src: 'img9.jpg'
  }, {
    index: '20',
    src: 'img10.jpg'
}]